spring.application.name=portafolio


# --- perfiles ---
# Activador dinamico de perfil mediante Maven
spring.profiles.include=local
spring.profiles.active=@activatedProfile@


server.port=8081
servidor.http=localhost
##############################################################

# En desarrollo el "cache" del servidor (false), en produccion "true"
spring.thymeleaf.cache=false
#############################################################

# --- Estrictamente debugging ---
# Para eliminar mensajes invasivos de Spring
spring.main.banner-mode=off

# Para definir el formato de despliegue de fecha/hora del log en la consola
logging.pattern.dateformat=hh:mm

# Otros logging
logging.level.web=DEBUG

# define detalle de logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.type.descriptor.sql.BasicBinder=TRACE

# mostrar queries sql en output
spring.jpa.show-sql=true

# formato a sql para legibilidad
spring.jpa.properties.hibernate.format_sql=true
#############################################################

# --- SQL ---
# hace que springboot corra schema.sql y data.sql en /resources, 
# SOLO ese path y con nomenclatura adecuada para orden, sino hay que declarar manualmente
spring.sql.init.mode=always

# no aborta si falla script sql, en caso de que ya exista bd
spring.sql.init.continue-on-error=true

# - COMPORTAMIENTO SPRING -
# para que hibernate no altere estructura de bd tras leer domain
# spring.jpa.hibernate.ddl-auto=validate 

# para que spring pueda crear tablas desde domain y scripts en resources
spring.jpa.hibernate.ddl-auto=update