# --- Base de datos en Aiven ---
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=avnadmin
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#############################################################

# --- Firebase Storage ---
# Esta informacion se utiliza para obtener acceso a su storage.
firebase.bucket.name=sc403-93f53.firebasestorage.app
firebase.storage.path=portafolio
firebase.json.path=firebase
# no se usa por cambios en StorageConfig.java (ruta hardcoded), 
# pero se pone para evitar errores de compilacion
firebase.json.file=firebase-auth.json
#############################################################

# --- Mailing ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
#############################################################

# --- debugging ---
# valores: update, validate, create-drop, viable cambiar a create momentaneamente para desplegar, correr y luego reajustar
spring.jpa.hibernate.ddl-auto=update

# never = bajo ninguna circumstancia corre scripts, igual por usar aiven ya deberia existir estructura
# valores:  always, never
spring.sql.init.mode=never

# no aborta si falla script sql
spring.sql.init.continue-on-error=true

# mostrar queries sql en output
spring.jpa.show-sql=false

# formato a sql para legibilidad
spring.jpa.properties.hibernate.format_sql=false
#############################################################