# Conexion a BD local en mariadb
spring.datasource.url=jdbc:mariadb://localhost:3306/techshop

# Usuario y clave segun script sql
spring.datasource.username=usuario_prueba
spring.datasource.password=Usuar1o_Clave.

# Driver y comunicacion
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver